name: Reportar un Error (Bug)
description: Crea un informe para ayudarnos a mejorar
title: "[Bug]: "
labels: bug
body:
- type: textarea
  attributes:
    label: Descripción del error
    description: Una descripción clara y concisa de cuál es el error.
  validations:
    required: true

- type: textarea
  attributes:
    label: Pasos para reproducir
    description: Pasos para reproducir el comportamiento.
    placeholder: |
      1. Ve a '...'
      2. Haz clic en '...'
      3. Desplázate hasta '...'
      4. Observa el error
  validations:
    required: true

- type: textarea
  attributes:
    label: Comportamiento esperado
    description: Una descripción clara y concisa de lo que esperabas que sucediera.
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs
    description: |
      Para que un reporte de error sea válido, es necesario incluir los logs de ChemaModsV2.
      Puedes encontrarlos en `%appdata%/ChemaModsV2/cout.log`. Aunque creas que el archivo de logs no es útil, te pedimos que lo incluyas.
      
      **Consejo:** Para subir fácilmente el archivo, renómbralo de `cout.log` a `cout.txt`, o comprímelo en un .zip. Luego puedes arrastrar y soltar el archivo aquí.
  validations:
    required: true

- type: textarea
  attributes:
    label: Capturas de pantalla / Video
    description: |
      Si crees que el problema se explica mejor con capturas de pantalla o un video, agrégalos aquí.
      
      **Consejo:** Puedes adjuntar imágenes haciendo clic en esta área para resaltarla y luego arrastrando los archivos.
    value: |
      <!-- arrastra y suelta tus imágenes o video(s) aquí -->
  validations:
    required: false

- type: dropdown
  attributes:
    label: Tienda / Launcher
    description: ¿Qué launcher o tienda usas para ejecutar el juego?
    multiple: false
    options:
      - Steam
      - Epic Games
      - Rockstar
      - Otro (por favor indícalo en "Contexto adicional")
  validations:
    required: true

- type: dropdown
  attributes:
    label: Idioma del juego (GTA 5)
    description: ¿En qué idioma tienes configurado GTA 5?
    multiple: false
    options:
      - English
      - French
      - Italian
      - German
      - Spanish
      - Japanese
      - Russian
      - Polish
      - Brazilian Portuguese
      - Traditional Chinese
      - Simplified Chinese
      - Latin American Spanish
      - Korean
  validations:
    required: true

- type: dropdown
  attributes:
    label: Idioma de ChemaModsV2
    description: ¿En qué idioma usas ChemaModsV2?
    multiple: false
    options:
      - English (US)
      - Español (España)
      - Français (FR)
      - Italiano (IT)
      - Portuguese (BR)
      - Русский (RU)
      - Chinese (CN)
      - Chinese (TW)
      - Korean (KR)
  validations:
    required: true

- type: textarea
  attributes:
    label: Contexto adicional
    description: Agrega cualquier otra información sobre el problema aquí.
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Versión utilizada
    description: Queremos confirmar que este problema existe en la última versión oficial de ChemaModsV2, no en un fork ni en tu propia compilación.
    options:
      - label: He confirmado que el problema existe en la última versión oficial de ChemaModsV2
        required: true

- type: checkboxes
  attributes:
    label: Sin co-loading
    description: Asegúrate de probar ChemaModsV2 sin cargar otros mods (Menyoo, Stand, etc.) primero. Si el problema no aparece sin ellos, verifica si crees que el error es nuestro o del otro producto.
    options:
      - label: He probado esto sin cargar ningún otro mod (co-loading).
        required: true