name: Problema de compilación
description: Informar sobre un problema al compilar ChemaModsV2
title: "[Compilación]: "
labels: build
body:
- type: textarea
  attributes:
    label: Describe los problemas de compilación
    description: Una descripción clara y concisa de cuál es el problema.
  validations:
    required: true
- type: textarea
  attributes:
    label: Capturas de pantalla y/o registros (logs)
    description: "Consejo: Puedes adjuntar imágenes o archivos de registro haciendo clic en esta área para resaltarla y luego arrastrando los archivos dentro."
    value: |
      ```
      <pega tus registros aquí>
      ```
  validations:
    required: false
- type: dropdown
  attributes:
    label: IDE/Compilador
    description: ¿Qué IDE usas para compilar ChemaModsV2?
    multiple: false
    options:
      - Visual Studio 2022
      - Visual Studio Code
      - Línea de comandos
      - Otro (por favor, menciónalo en "Contexto adicional")
  validations:
    required: true
- type: textarea
  attributes:
    label: Contexto adicional
    description: Añade cualquier otro contexto sobre el problema aquí.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Guía de configuración
    description: Confirmas que has seguido la guía de configuración para compilar el menú.
    options:
      - label: Confirmo que he seguido la guía de configuración correctamente.
        required: true
- type: checkboxes
  attributes:
    label: Código fuente de ChemaModsV2
    description: Confirmas que no has modificado ChemaModsV2 y que estás compilando la última versión del código fuente.
    options:
      - label: He confirmado que este es un problema al compilar ChemaModsV2 sin modificar.
        required: true