name: Problema de Compilación (Build)
description: Reporta un problema al compilar ChemaModsV2
title: "[Build]: "
labels: build
body:
- type: textarea
  attributes:
    label: Descripción del problema de compilación
    description: Una descripción clara y concisa del problema que estás teniendo.
  validations:
    required: true
- type: textarea
  attributes:
    label: Capturas de pantalla y/o Logs
    description: "Consejo: Puedes adjuntar imágenes o archivos de log haciendo clic en esta área para resaltarla y luego arrastrando los archivos."
    value: |
      ```
      <pega tus logs aqui>
      ```
  validations:
required: false
- type: dropdown
attributes:
label: IDE / Compilador
description: ¿Qué IDE o método usas para compilar ChemaModsV2?
multiple: false
options:
- Visual Studio 2022
- Visual Studio Code
- Línea de comandos (Command Line)
- Otro (por favor indícalo en "Contexto adicional")
validations:
required: true
- type: textarea
attributes:
label: Contexto adicional
description: Agrega cualquier otra información sobre el problema aquí.
validations:
required: false
- type: checkboxes
attributes:
label: Guía de configuración
description: Confirmas que seguiste correctamente la guía de configuración para compilar el menú.
options:
- label: Confirmo que seguí correctamente la guía de configuración.
  required: true
- type: checkboxes
attributes:
label: Código fuente de ChemaModsV2
description: Confirmas que no has modificado ChemaModsV2 y estás compilando la última versión del código fuente original.
options:
- label: He confirmado que este es un problema al compilar ChemaModsV2 sin modificaciones.
  required: true