name: Solicitud de Nueva Funcionalidad (Feature Request)
description: Sugiere una idea para mejorar este proyecto
title: "[Request]: "
labels: request
body:
- type: textarea
  attributes:
    label: Problema
    description: "¿Tu solicitud de funcionalidad está relacionada con un problema? Por favor descríbelo."
    placeholder: "Una descripción clara y concisa del problema. Ej: Siempre me frustra cuando [...]"
  validations:
    required: false
- type: textarea
  attributes:
    label: Solución propuesta
    description: "Describe la solución que te gustaría implementar"
    placeholder: "Una descripción clara y concisa de lo que quieres que suceda."
  validations:
    required: true
- type: textarea
  attributes:
    label: Razón
    description: Proporciona el razonamiento
    placeholder: "Explícanos por qué te gustaría que agregáramos esto a ChemaModsV2."
  validations:
    required: true
- type: textarea
  attributes:
    label: Contexto adicional
    description: |
      Agrega cualquier otra información sobre tu solicitud aquí.

      Consejo: Puedes adjuntar imágenes o archivos haciendo clic en esta área para resaltarla y luego arrastrando los archivos.
  validations:
    required: false
