name: Solicitud de Mejora (Improvement)
description: Mejora una funcionalidad existente en ChemaModsV2
title: "[Improvement]: "
labels: improvement
body:
- type: textarea
  attributes:
    label: ¿Qué funcionalidad quieres mejorar?
    description: "Explícanos qué funcionalidad te gustaría ver mejorada y qué te gustaría cambiar de ella."
    placeholder: "Me gustaría que la función Configuración -> ESP estuviera estructurada de forma diferente, actualmente es poco claro cómo funcionan todas las opciones juntas."
  validations:
    required: false
- type: textarea
  attributes:
    label: Razón
    description: Proporciona el razonamiento
    placeholder: "Explícanos por qué te gustaría que mejoráramos esta funcionalidad en ChemaModsV2."
  validations:
    required: true
- type: textarea
  attributes:
    label: Contexto adicional
    description: |
      Agrega cualquier otra información sobre tu solicitud aquí.

      Consejo: Puedes adjuntar imágenes o archivos haciendo clic en esta área para resaltarla y luego arrastrando los archivos.
  validations:
    required: false
