name: Autolocker

on:
  pull_request_target:
    types: [closed]

# Permisos necesarios para bloquear issues/PRs
permissions:
  issues: write
  pull-requests: write

jobs:
  autolock:
    # if: ${{ github.event.pull_request.merged }}   # Descomenta esta línea si quieres que solo se ejecute cuando la PR se MERGEA
    runs-on: ubuntu-latest
    name: Autolocker
    steps:
      - name: Bloquear PRs cerrados o mergeados
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.lock({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              lock_reason: "resolved"   // Opciones: "off-topic", "too heated", "resolved", "spam"
            })