name: CI

on:
  pull_request:
    paths:
      - src/**
      - cmake/**
      - CMakeLists.txt
      - .github/workflows/ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: Verificar versión de CMake
        run: cmake --version

      - name: Configurar entorno MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generar proyecto CMake
        run: cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S. -Bbuild -G Ninja

      - name: Compilar DLL 64-bit Release
        run: cmake --build ./build --config RelWithDebInfo --target ChemaModsV2 --

      - name: Verificar si la DLL se compiló correctamente
        run: if (-Not (Test-Path -path "build/ChemaModsV2.dll")) {throw 1}

      - name: Renombrar DLL a ChemaModsV2-dev-{SHA}.dll
        run: |
          del ChemaModsV2-dev-*.dll
          del ChemaModsV2-dev-*.pdb
          ren ChemaModsV2.dll ChemaModsV2-dev-${{github.sha}}.dll
          ren ChemaModsV2.pdb ChemaModsV2.pdb
        working-directory: build/

      - name: Subir Artefacto (DLL)
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            build/ChemaModsV2-dev-*.dll

      - name: Subir Artefacto (PDB)
        uses: actions/upload-artifact@v4
        with:
          name: pdb
          path: |
            build/ChemaModsV2.pdb