name: Comentar en Pull Request

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  pr_comment:
    # Solo se ejecuta si el workflow CI se completó con éxito y viene de un Pull Request
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el número del Pull Request
        run: |
          # Buscar el PR asociado al commit usando la API de GitHub
          PR_RAW=$(curl 'https://api.github.com/search/issues?q=${{ github.event.workflow_run.head_commit.id }}')
          
          # Extraer el número del PR (filtrando solo los de este repositorio)
          PR_NUM=$(echo $PR_RAW | jq '.items | map(select(.repository_url=="https://api.github.com/repos/${{ github.repository }}")) | .[0].number')
          
          echo "PR_NUM=${PR_NUM}" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          # Este script es de dominio público (basado en oprypin/nightly.link)
          # Modificado para soportar PRs de forks
          script: |
            async function upsertComment(owner, repo, issue_number, purpose, body) {
              const {data: comments} = await github.rest.issues.listComments(
                {owner, repo, issue_number});
              const marker = `<!-- bot: ${purpose} -->`;
              body = marker + "\n" + body;
              const existing = comments.filter((c) => c.body.includes(marker));
              if (existing.length > 0) {
                const last = existing[existing.length - 1];
                core.info(`Actualizando comentario ${last.id}`);
                await github.rest.issues.updateComment({
                  owner, repo,
                  body,
                  comment_id: last.id,
                });
              } else {
                core.info(`Creando comentario en issue / PR #${issue_number}`);
                await github.rest.issues.createComment({issue_number, body, owner, repo});
              }
            }

            const {owner, repo} = context.repo;
            const run_id = '${{github.event.workflow_run.id}}';
            const artifacts = await github.paginate(
              github.rest.actions.listWorkflowRunArtifacts, {owner, repo, run_id});

            if (!artifacts.length) {
              return core.error(`No se encontraron artefactos`);
            }

            let body = `📥 Descarga los artefactos de esta Pull Request:\n`;
            for (const art of artifacts) {
              body += `\n* [${art.name}.zip](https://nightly.link/${owner}/${repo}/actions/artifacts/${art.id}.zip)`;
            }

            core.info("Cuerpo del mensaje:", body);
            await upsertComment(owner, repo, ${{ env.PR_NUM }}, "nightly-link", body);